title: Twileloop.SafeConfig
description: "Compiletime validation of your appsettings.json using any custom fluent validators"
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
github:
  zip_url: https://github.com/sangeethnandakumar/Twileloop.SafeConfig/releases
  tar_url: https://www.nuget.org/packages/Twileloop.SafeConfig
